//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Pausenzeiten", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class Pausenzeiten : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private bool AktuellPauseField;
    
    private string[] PauseField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool AktuellPause
    {
        get
        {
            return this.AktuellPauseField;
        }
        set
        {
            this.AktuellPauseField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string[] Pause
    {
        get
        {
            return this.PauseField;
        }
        set
        {
            this.PauseField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceTOP")]
public interface IServiceTOP
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTOP/LiesZahl", ReplyAction="http://tempuri.org/IServiceTOP/LiesZahlResponse")]
    string LiesZahl(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTOP/LiesZahl", ReplyAction="http://tempuri.org/IServiceTOP/LiesZahlResponse")]
    System.Threading.Tasks.Task<string> LiesZahlAsync(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTOP/LiesPausenzeiten", ReplyAction="http://tempuri.org/IServiceTOP/LiesPausenzeitenResponse")]
    Pausenzeiten LiesPausenzeiten(bool Pause);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTOP/LiesPausenzeiten", ReplyAction="http://tempuri.org/IServiceTOP/LiesPausenzeitenResponse")]
    System.Threading.Tasks.Task<Pausenzeiten> LiesPausenzeitenAsync(bool Pause);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceTOPChannel : IServiceTOP, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceTOPClient : System.ServiceModel.ClientBase<IServiceTOP>, IServiceTOP
{
    
    public ServiceTOPClient()
    {
    }
    
    public ServiceTOPClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceTOPClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceTOPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceTOPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string LiesZahl(int value)
    {
        return base.Channel.LiesZahl(value);
    }
    
    public System.Threading.Tasks.Task<string> LiesZahlAsync(int value)
    {
        return base.Channel.LiesZahlAsync(value);
    }
    
    public Pausenzeiten LiesPausenzeiten(bool Pause)
    {
        return base.Channel.LiesPausenzeiten(Pause);
    }
    
    public System.Threading.Tasks.Task<Pausenzeiten> LiesPausenzeitenAsync(bool Pause)
    {
        return base.Channel.LiesPausenzeitenAsync(Pause);
    }
}
